#!/bin/sh

hdfs dfs -rm -r -f /user/KapiWowBigdata/output-spark

input_directory=/bigdata-course/datasets/text
output_directory=/user/$USER/output-spark
rm -rvf $output_directory
spark-submit --master yarn \
    --jars /gfs/jars/lucene/6.2.0/lucene-core-6.2.0.jar,/gfs/jars/lucene/6.2.0/lucene-analyzers-common-6.2.0.jar,/gnu/store/dcbpxj45hw3mpwrh54palw68icflrd6a-spark-3.0.0-preview2/jars/glusterfs-hadoop-2.3.13.jar,   \
    --class src.Main \
    build/wordcount.jar $input_directory $output_directory
